### ISSUE TITLE
Json serialization

### ISSUE THREAD

**Issue by MrIzi** [Camphul/CoinMarketCap-API#3]
Hi Lucas

nice job, thx !
 I would be interested but i wonder why the api doesn't produce json formatted result like this:

{
	"PriceQuote": {
		"price": 7094.8268024,
		"dayVolume": 3.9292290664E9,
		"marketCap": 1.20927151089E11,
		"hourChange": 0.28,
		"dayChange": 0.45,
		"weekChange": -3.03
	}
}

It would be much easier to automatically deserialize the response in a java program !

MrIzi

**Comment by Camphul** [comment]
I don't really get your issue but I think I understand your question(btw I'm not the developer of their API, I just wrote a Java implementation).

CoinMarketCap allows you to fetch multiple currencies. This is return in a map of PriceQuotes. Or do you want to serialize the Java object to Json again?
